log:
  level: debug
  file: '/tmp/mosdns.log'

data_providers:
  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

plugins:
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 17200
  
  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # ipset 写入应答 IP 到系统 ipset
  - tag: blacklist
    type: ipset
    args:
      set_name4: 'blacklist'
      set_name6: ''
      mask4: 24
      mask6: 32

################ DNS #################
  # 阿里 dns
  - tag: ali
    type: fast_forward
    args:
      upstream:
        - addr: "223.5.5.5"
        - addr: "https://dns.alidns.com/dns-query" 
          dial_addr: "223.5.5.5"            
          trusted: true 
        - addr: "tls://dns.alidns.com"
          dial_addr: "223.5.5.5"
          trusted: true       

  # dnspod
  - tag: dnspod
    type: fast_forward
    args:
      upstream:
        - addr: "119.29.29.29"
        - addr: "https://doh.pub/dns-query" 
          dial_addr: "1.12.12.12"
          trusted: true 
        - addr: "tls://dot.pub" 
          dial_addr: "1.12.12.12"
          trusted: true           

  # 本地 dns 备用
  - tag: localdns
    type: fast_forward
    args:
      upstream:
        - addr: "119.29.29.29"
        - addr: "101.226.4.6"
        - addr: "223.5.5.5"

  # google dns
  - tag: google
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns.google/dns-query" 
          dial_addr: "8.8.4.4"
          trusted: true 
        - addr: "tls://dns.google" 
          dial_addr: "8.8.4.4"
          trusted: true
      
  # cloudflare
  - tag: cloudflare
    type: fast_forward
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query" 
          dial_addr: "1.1.1.1"
          trusted: true 
        - addr: "tls://cloudflare-dns.com" 
          dial_addr: "1.1.1.1"
          trusted: true 
          
  # doq 备用
  - tag: adguard
    type: forward
    args:
      upstream:
        - addr: "quic://dns-unfiltered.adguard" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "94.140.14.140"
            - "94.140.14.141"
          trusted: true # 是否是可信服务器

  # local 序列
  - tag: forward_local
    type: sequence
    args:
      exec:
        - primary:
          - parallel: # 并行
              - - "dnspod" # 执行序列 #2。
              - - "ali"
          secondary:
            - localdns # 备用本地
          fast_fallback: 400 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  # remote 序列
  - tag: forward_remote
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "google" # 执行序列 #1。
                - - "cloudflare" # 执行序列 #2。
          secondary:
            - adguard # 备用 adguard
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true


  ################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn,apple-cn,steam@cn'        

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads-all'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  - tag: main_sequence
    type: sequence
    args:
      exec:      
        # - hosts
        - _misc_optm
        - lazy_cache
        - _no_ecs

        # ipset 写入应答 IP 到系统 ipset
        - blacklist

        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return        

        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - if: response_has_local_ip
              exec:
                - _return
        
        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4               # 优先 IPv4
            - forward_remote             # 用远程服务器获取应答
            - modify_ttl
            - if: "! response_has_local_ip"
              exec:
                - _return
        
        # 剩下的未知域名用 IP 分流。原理类似 ChinaDNS，但更稳定。
        # 详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - forward_local     # 本地服务器获取应答。
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response            # 丢掉。
          secondary:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
          fast_fallback: 300  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。单位: 毫秒。
          always_standby: true

servers:
  - exec: main_sequence
    listeners:
      # - protocol: udp
      #   addr: "[::1]:5335"
      # - protocol: tcp
      #   addr: "[::1]:5335"
      - protocol: udp
        addr: "0.0.0.0:5335"
      - protocol: tcp
        addr: "0.0.0.0:5335"