log:
  level: error
  file: '/tmp/mosdns.log'

# 数据源设置
data_providers:
  - tag:                   geosite
    file:                  "/usr/share/v2ray/geosite.dat"
    auto_reload:           true

  - tag:                   geoip
    file:                  "/usr/share/v2ray/geoip.dat"
    auto_reload:           true

plugins:
  - tag: "360dns"
    type: fast_forward
    args:
      upstream:
        - addr: https://doh.360.cn/dns-query
          dial_addr: '36.99.170.86:443'

  - tag: "aliyun"
    type: fast_forward
    args:
      upstream:
        - addr: https://dns.alidns.com/dns-query
          dial_addr: '223.5.5.5:443'
        - addr: tls://223.6.6.6
          trusted: true
  - tag: "dnspod"
    type: fast_forward
    args:
      upstream:
        - addr: https://doh.pub/dns-query
          dial_addr: '1.12.12.12:443'
        - addr: tls://120.53.53.53
          trusted: true
          
  - tag: "google"
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
        - addr: 'tls://8.8.4.4'
          trusted: true
      
  - tag: "cloudflare"
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://1.0.0.1'
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: '1.1.1.1:443'
          trusted: true

  - tag: "opendns"
    type: fast_forward
    args:
      upstream:
        - addr: "https://doh.opendns.com/dns-query"
          dial_addr: '146.112.41.2'
          trusted: true
  - tag: "quad9"
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns10.quad9.net/dns-query" # 服务器地址
          dial_addr: 9.9.9.10
          trusted: true # 是否是可信服务器
        - addr: "https://dns10.quad9.net/dns-query" # 服务器地址
          dial_addr: 149.112.112.10
          trusted: true # 是否是可信服务器
  # doq 备用
  - tag: adguard
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns-unfiltered.adguard.com/dns-query" # 服务器地址
          dial_addr: 94.140.14.140
          trusted: true # 是否是可信服务器
        - addr: "https://dns-unfiltered.adguard.com/dns-query" # 服务器地址
          dial_addr: 94.140.14.141
          trusted: true # 是否是可信服务器
          
  - tag: localdns
    type: fast_forward
    args:
      upstream:
        - addr: "114.114.114.114"

  # local 序列
  - tag: forward_local
    type: sequence
    args:
      exec:
        - primary:
          - parallel: # 并行
              - - "dnspod" # 执行序列 #2。
              - - "aliyun"
              - - "360dns"
          secondary:
            - localdns # 备用本地
          fast_fallback: 400 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  # remote 序列
  - tag: forward_remote
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "google" # 执行序列 #1。
                - - "cloudflare" # 执行序列 #2。
                - - "opendns"
                - - "quad9"
          secondary:
            - adguard # 备用 adguard
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  - tag: "mem_cache"
    type: cache
    args:
      size: 2048
      lazy_cache_ttl: 17200
  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # ipset 写入应答 IP 到系统 ipset
  - tag: remote_ipset
    type: 'ipset'
    args:
      set_name4: 'blacklist'   # 如果非空，存放 ipv4 地址到这个表。这个表属性 family 需为 `inet`。
      set_name6: ''   # 如果非空，存放 ipv6 地址到这个表。这个表属性 family 需为 `inet6`。
      mask4: 24       # 写入 ipv4 地址时使用的掩码。默认: 24。
      mask6: 32       # 写入 ipv6 地址时使用的掩码。默认: 32。

  - tag: "query_is_ad_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:category-ads-all"

  # 匹配本地域名的插件
  - tag: "query_is_local_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:icloud,apple-cn,cn"

  - tag: "query_is_gfw"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:greatfire,gfw"

  # 匹配本地 IP 的插件
  - tag: "response_has_local_ip"
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - mem_cache

        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return
        - if: query_is_gfw
          exec:
            - forward_remote
            - remote_ipset
            - _return
        # 本地服务器获取应答。
        - forward_local
        - modify_ttl    

  - tag: second_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - mem_cache

        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return
        # 已知的本地域名
        - if: query_is_local_domain   
          exec:
            # 用本地服务器获取应答
            - forward_local
            - modify_ttl
            - _return
        - _prefer_ipv4
        - forward_remote
        - modify_ttl
        - remote_ipset

# 服务器设置
servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: :5335
      - protocol: tcp
        addr: :5335
  - exec: second_sequence
    listeners:
      - protocol: udp
        addr: :5336
      - protocol: tcp
        addr: :5336
